run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - nilnil
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-blank: true
