sonar.projectKey=Elysium-Labs-EU_eos
sonar.organization=elysium-labs-eu

sonar.sources=.
sonar.exclusions=**/*_test.go,**/__benchmarks__/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
